steps:
- uses: actions/checkout@v2
- uses: open-watcom/setup-watcom@v0
  with:
    version: "2.0"
- run: |
    wcl386 -zq -d+ -i"${{ env.WATCOM }}/h" -w3 -bt=dos -d2 -fomain.c.obj -c -cc main.c
    wlink option quiet name hello.exe opt map system dos4g debug all file main.c.obj
- run: |
    cmake -S . -B build -G "Watcom WMake" -D CMAKE_SYSTEM_NAME=DOS
    cmake --build build