name: Open Watcom Setup

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install depedencies
      run: sudo apt-get install qemu-system-x86 make nasm bochs-x bochsbios vgabios mtools xorriso

    - name: Set up Open Watcom
      uses: open-watcom/setup-watcom@v0
      with:
        version: '2.0'  # specify the version of Open Watcom to use

    - name: Run Makefile
      run: make