name: Open Watcom Setup

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Open Watcom
      uses: open-watcom/setup-watcom@v0
      with:
        version: '2.0'  # specify the version of Open Watcom to use

    - name: Check ld32 version
      run: ls /home/runner/watcom/binl